#-------------------------------------------------------------------------------
# terrimporter configuration, adjust as needed.
#-------------------------------------------------------------------------------
# Important notes READ THEM:
# * Don't mess with indentation!
# * All local paths are relative to the running directory
# * multiple entries have the following format (stylesheet replacement example):
# - what: /replacethis/
#   with: /withthis/
# - what: /another/
#   with: /replacement/

# APPLICATION
# url: Terrific base url
application_url: http://terrific.project.url

# STYLESHEETS
stylesheets:
# The destination directory, relative from the current running directory
  destination_path: public/stylesheets/
# Additional stylesheets, you can but don't have to add the .css extension
#  styles: ie, ie6, ie7.css
# replace_strings: Define string replacements in css files 
# (use multiple replacements by repeating the '-what: with:' statements)
  replace_strings:
#    - what: /img/     # What to replace, format: [string] or [r/regex/]
#      with: /images/  # Replace with [string]

# JAVASCRIPTS
javascripts:
# Destination path of the javascript base.js file
  destination_path: public/javascripts/
# Dynamic libraries definition, you can but don't have to add the .js extension
#  dynamic_libraries: foo_lib.js bar_lib.js
# Destination path of the dynamic libraries (relative)
#  libraries_destination_path:  public/javascripts/libraries/

# IMAGES - multiple entries allowed
images:
#  - server_path: / # The server path is appended to the image_server_path
#    destination_path: public/images/  # The relative destination path
#    file_types: jpg, png, gif  # Image file endings to be downloaded

# MODULES - multiple entries allowed
modules:
#  - name:                 #Module name
#    skin:                 #Skin name, if used
#    module_template:      #The module template used, required
#    template_only: false  #Only import template without surrounding divs, default: false
#    destination_path: #Destination path of

#-------------------------------------------------------------------------------
# ADVANCED EDITING - Only edit the following if you know what you're doing...
# ------------------------------------------------------------------------------
# The settings below are added as query string parameters to the export path
export_settings:
  debug: false      # False compacts the base.js and base.css files
  cache: false      # You most probably won't have to change this
  layout: project   # You most probably won't have to change this

# The server side library source path for the dynamic libraries
libraries_server_path: /js/libraries/dynamic

# The server side image base path
image_server_path: /img
