#-------------------------------------------------------------------------------
# terrimporter configuration, adjust as needed.
#-------------------------------------------------------------------------------
# Important notes READ:
# * Don't mess with indentation!
# * All local paths are relative to the current working directory
# * Target_dir always refers to the local destination "target" directory
# * multiple entries have the following format (stylesheet replacement example):
# - what: /replacethis/
#   with: /withthis/
# - what: /another/
#   with: /replacement/


# APPLICATION
application_url: http://terrific.project.url  # Terrific project base url

# STYLESHEETS
stylesheets:
  target_dir: public/stylesheets/
#  styles: ie, ie6, ie7.css       # Additional stylesheets, .css extension optional
  replace:                        # Define multiple string replacements in css files
#    - what: /img/                # What to replace, format: [string] or [r/regex/]
#      with: /images/             # Replace with [string]

# JAVASCRIPTS
javascripts:
  target_dir: public/javascripts/
#  libraries: foo_lib.js bar_lib.js # Dynamic libraries definition, .css extension optional
#  libraries_target_dir:  public/javascripts/libraries/ #  target_dir is used if unspecified
#  plugins: dynamic.js  # Dynamic plugins definition, .css extension optional
#  plugins_target_dir: public/javascript/plugins/ # target_dir is used if unspecified

# IMAGES - multiple entries allowed
images:
#  - server_dir: / # The server directory is appended to images_server_dir
#    target_dir: public/images/
#    file_types: jpg, png, gif  # Image file endings to be downloaded

# MODULES - multiple entries allowed
modules:
#  - name: samplemodule    #Module name
#    skin:                 #Skin name, if used
#    module_template: tmpl #The module template used, required
#    template_only: false  #Only import template without surrounding divs, default: false
#    target_dir: public/modules/

#-------------------------------------------------------------------------------
# ADVANCED EDITING - Only edit the following if you know what you're doing...
# ------------------------------------------------------------------------------
# The settings below are added as query string parameters to the export path
export_settings:
  debug: false      # False compacts the base.js and base.css files
  cache: false      # You most probably won't have to change this
  layout: project   # You most probably won't have to change this

libraries_server_dir: /js/libraries/dynamic # Server side libraries base path
plugins_server_dir: /js/plugins/dynamic # Server side plugins base path
images_server_dir: /img # Server side image base path
