# Terrific import configuration file, adjust as needed.
# -----------------------------------------------------
# url: Terrific base url
application_url: http://terrific.url

# Import settings for stylesheets
stylesheets:
# The destination directory, relative from the current running directory
  dest: public/stylesheets/
# Name of the stylesheets (except base.css), space separated without the .css extension. ex: ie ie6 ie7 ie8
#  styles: ie ie6 ie7
# replace: Define path replacements after the stylesheets have been downloaded
# you can define multiple replacements by repeating the '-what: with:' statements
  replace:
#    - what: /img/     # What to replace, format: string or r/regular expression/
#      with: /images/  # Replace with this (string)

# Import settings for javascripts
javascripts:
# Destination path of the javascript base.js file
  dest: public/javascripts/
# Dynamic libraries definition, space separated without the .js extension. ex: warning pngfix
#  dynamic_libraries: foo_lib bar_lib
# Destination of the dynamic libraries relative to the 'relative_destination_path' path. '/' means they're included in 'relative_destination_path'
#  libraries_dest: /

# Define the images to be downloaded, the terrific base path is always "img", so the src root is "img/"
# each of the entries describes one path for images to be downloaded
images:
#  - src: /                # The source path, "/" means "img/"
#    dest: public/images/  # The destination directory, relative from the current running directory
#    types: jpg png gif    # The image endings to be downloaded, specified as a space separated string


# ADVANCED EDITING
# Only edit the following if you know what you're doing...


# The base.js/.css export path
export_path:  /terrific/base/%2$s/public/%1$s/base/base.%1$s.php

# The settings below are added as query parameters for base.js and base.css
export_settings:
  layout: project # You most probably won't have to change this
  debug: false    # False compacts the base.js and base.css files
  cache: false    # You most probably won't have to change this

# The library source path for the dynamic libraries.
libraries_source_path: /js/libraries/dynamic

# The terrific image base path.
image_base_path: /img
